# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/estilon/Documents/Parale-Final

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/estilon/Documents/Parale-Final

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/estilon/Documents/Parale-Final/CMakeFiles /home/estilon/Documents/Parale-Final/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/estilon/Documents/Parale-Final/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named STACK

# Build rule for target.
STACK: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 STACK
.PHONY : STACK

# fast build rule for target.
STACK/fast:
	$(MAKE) -f CMakeFiles/STACK.dir/build.make CMakeFiles/STACK.dir/build
.PHONY : STACK/fast

#=============================================================================
# Target rules for targets named LOAD

# Build rule for target.
LOAD: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LOAD
.PHONY : LOAD

# fast build rule for target.
LOAD/fast:
	$(MAKE) -f CMakeFiles/LOAD.dir/build.make CMakeFiles/LOAD.dir/build
.PHONY : LOAD/fast

#=============================================================================
# Target rules for targets named SERIAL

# Build rule for target.
SERIAL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SERIAL
.PHONY : SERIAL

# fast build rule for target.
SERIAL/fast:
	$(MAKE) -f CMakeFiles/SERIAL.dir/build.make CMakeFiles/SERIAL.dir/build
.PHONY : SERIAL/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

paralelo/load/LOAD.o: paralelo/load/LOAD.cpp.o

.PHONY : paralelo/load/LOAD.o

# target to build an object file
paralelo/load/LOAD.cpp.o:
	$(MAKE) -f CMakeFiles/LOAD.dir/build.make CMakeFiles/LOAD.dir/paralelo/load/LOAD.cpp.o
.PHONY : paralelo/load/LOAD.cpp.o

paralelo/load/LOAD.i: paralelo/load/LOAD.cpp.i

.PHONY : paralelo/load/LOAD.i

# target to preprocess a source file
paralelo/load/LOAD.cpp.i:
	$(MAKE) -f CMakeFiles/LOAD.dir/build.make CMakeFiles/LOAD.dir/paralelo/load/LOAD.cpp.i
.PHONY : paralelo/load/LOAD.cpp.i

paralelo/load/LOAD.s: paralelo/load/LOAD.cpp.s

.PHONY : paralelo/load/LOAD.s

# target to generate assembly for a file
paralelo/load/LOAD.cpp.s:
	$(MAKE) -f CMakeFiles/LOAD.dir/build.make CMakeFiles/LOAD.dir/paralelo/load/LOAD.cpp.s
.PHONY : paralelo/load/LOAD.cpp.s

paralelo/load/ThreadPool.o: paralelo/load/ThreadPool.cpp.o

.PHONY : paralelo/load/ThreadPool.o

# target to build an object file
paralelo/load/ThreadPool.cpp.o:
	$(MAKE) -f CMakeFiles/LOAD.dir/build.make CMakeFiles/LOAD.dir/paralelo/load/ThreadPool.cpp.o
.PHONY : paralelo/load/ThreadPool.cpp.o

paralelo/load/ThreadPool.i: paralelo/load/ThreadPool.cpp.i

.PHONY : paralelo/load/ThreadPool.i

# target to preprocess a source file
paralelo/load/ThreadPool.cpp.i:
	$(MAKE) -f CMakeFiles/LOAD.dir/build.make CMakeFiles/LOAD.dir/paralelo/load/ThreadPool.cpp.i
.PHONY : paralelo/load/ThreadPool.cpp.i

paralelo/load/ThreadPool.s: paralelo/load/ThreadPool.cpp.s

.PHONY : paralelo/load/ThreadPool.s

# target to generate assembly for a file
paralelo/load/ThreadPool.cpp.s:
	$(MAKE) -f CMakeFiles/LOAD.dir/build.make CMakeFiles/LOAD.dir/paralelo/load/ThreadPool.cpp.s
.PHONY : paralelo/load/ThreadPool.cpp.s

paralelo/stack/STACK.o: paralelo/stack/STACK.cpp.o

.PHONY : paralelo/stack/STACK.o

# target to build an object file
paralelo/stack/STACK.cpp.o:
	$(MAKE) -f CMakeFiles/STACK.dir/build.make CMakeFiles/STACK.dir/paralelo/stack/STACK.cpp.o
.PHONY : paralelo/stack/STACK.cpp.o

paralelo/stack/STACK.i: paralelo/stack/STACK.cpp.i

.PHONY : paralelo/stack/STACK.i

# target to preprocess a source file
paralelo/stack/STACK.cpp.i:
	$(MAKE) -f CMakeFiles/STACK.dir/build.make CMakeFiles/STACK.dir/paralelo/stack/STACK.cpp.i
.PHONY : paralelo/stack/STACK.cpp.i

paralelo/stack/STACK.s: paralelo/stack/STACK.cpp.s

.PHONY : paralelo/stack/STACK.s

# target to generate assembly for a file
paralelo/stack/STACK.cpp.s:
	$(MAKE) -f CMakeFiles/STACK.dir/build.make CMakeFiles/STACK.dir/paralelo/stack/STACK.cpp.s
.PHONY : paralelo/stack/STACK.cpp.s

paralelo/stack/ThreadPool.o: paralelo/stack/ThreadPool.cpp.o

.PHONY : paralelo/stack/ThreadPool.o

# target to build an object file
paralelo/stack/ThreadPool.cpp.o:
	$(MAKE) -f CMakeFiles/STACK.dir/build.make CMakeFiles/STACK.dir/paralelo/stack/ThreadPool.cpp.o
.PHONY : paralelo/stack/ThreadPool.cpp.o

paralelo/stack/ThreadPool.i: paralelo/stack/ThreadPool.cpp.i

.PHONY : paralelo/stack/ThreadPool.i

# target to preprocess a source file
paralelo/stack/ThreadPool.cpp.i:
	$(MAKE) -f CMakeFiles/STACK.dir/build.make CMakeFiles/STACK.dir/paralelo/stack/ThreadPool.cpp.i
.PHONY : paralelo/stack/ThreadPool.cpp.i

paralelo/stack/ThreadPool.s: paralelo/stack/ThreadPool.cpp.s

.PHONY : paralelo/stack/ThreadPool.s

# target to generate assembly for a file
paralelo/stack/ThreadPool.cpp.s:
	$(MAKE) -f CMakeFiles/STACK.dir/build.make CMakeFiles/STACK.dir/paralelo/stack/ThreadPool.cpp.s
.PHONY : paralelo/stack/ThreadPool.cpp.s

sequencial/SERIAL.o: sequencial/SERIAL.cpp.o

.PHONY : sequencial/SERIAL.o

# target to build an object file
sequencial/SERIAL.cpp.o:
	$(MAKE) -f CMakeFiles/SERIAL.dir/build.make CMakeFiles/SERIAL.dir/sequencial/SERIAL.cpp.o
.PHONY : sequencial/SERIAL.cpp.o

sequencial/SERIAL.i: sequencial/SERIAL.cpp.i

.PHONY : sequencial/SERIAL.i

# target to preprocess a source file
sequencial/SERIAL.cpp.i:
	$(MAKE) -f CMakeFiles/SERIAL.dir/build.make CMakeFiles/SERIAL.dir/sequencial/SERIAL.cpp.i
.PHONY : sequencial/SERIAL.cpp.i

sequencial/SERIAL.s: sequencial/SERIAL.cpp.s

.PHONY : sequencial/SERIAL.s

# target to generate assembly for a file
sequencial/SERIAL.cpp.s:
	$(MAKE) -f CMakeFiles/SERIAL.dir/build.make CMakeFiles/SERIAL.dir/sequencial/SERIAL.cpp.s
.PHONY : sequencial/SERIAL.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... STACK"
	@echo "... LOAD"
	@echo "... SERIAL"
	@echo "... run"
	@echo "... paralelo/load/LOAD.o"
	@echo "... paralelo/load/LOAD.i"
	@echo "... paralelo/load/LOAD.s"
	@echo "... paralelo/load/ThreadPool.o"
	@echo "... paralelo/load/ThreadPool.i"
	@echo "... paralelo/load/ThreadPool.s"
	@echo "... paralelo/stack/STACK.o"
	@echo "... paralelo/stack/STACK.i"
	@echo "... paralelo/stack/STACK.s"
	@echo "... paralelo/stack/ThreadPool.o"
	@echo "... paralelo/stack/ThreadPool.i"
	@echo "... paralelo/stack/ThreadPool.s"
	@echo "... sequencial/SERIAL.o"
	@echo "... sequencial/SERIAL.i"
	@echo "... sequencial/SERIAL.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

